name: Go

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
  schedule:
    - cron: '0 10 * * 1' # run "At 10:00 on Monday"


jobs:

  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v5
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.5'

      - name: Install dependencies
        run: |
          go get .

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...